spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ORDER_PROCESSING
        username: root
        password: rootPassword
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            naming: 
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl